src/main/java/com/flutterwave/flutter/clientms/model/BaseModel.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flutterwave.flutter.clientms.model;

import com.flutterwave.flutter.clientms.model.maker.*;
import com.flutterwave.flutter.clientms.model.User;
import com.flutterwave.flutter.clientms.util.Status;
import java.util.Date;

/**
 *
 * @author emmanueladeyemi
 */
public abstract class BaseModel {
    
    public abstract User getApprovedBy();
    public abstract void setApprovedBy(User user);
    public abstract Date getApprovedOn();
    public abstract void setApprovedOn(Date approvedOn);
    public abstract Date getCreatedOn();
    public abstract void setCreatedOn(Date date);
    
}

src/main/java/com/flutterwave/flutter/clientms/controller/ChargeBackController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flutterwave.flutter.clientms.controller;

import com.flutterwave.flutter.clientms.dao.ChargeBackDao;
import com.flutterwave.flutter.clientms.dao.ProductDao;
import com.flutterwave.flutter.clientms.dao.maker.ChargeBackMDao;
import com.flutterwave.flutter.clientms.model.Log;
import com.flutterwave.flutter.clientms.service.LogService;
import com.flutterwave.flutter.clientms.util.LogDomain;
import com.flutterwave.flutter.clientms.util.LogLevel;
import com.flutterwave.flutter.clientms.util.LogState;
import com.flutterwave.flutter.clientms.util.LogStatus;
import com.flutterwave.flutter.clientms.util.PaginationHelper;
import com.flutterwave.flutter.clientms.viewmodel.ChargeBackFilter;
import com.flutterwave.flutter.core.exception.DatabaseException;
import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.inject.Named;
import org.apache.shiro.SecurityUtils;
import org.apache.shiro.session.Session;

/**
 *
 * @author emmanueladeyemi
 */
@Named(value = "chargebackController")
@SessionScoped
public class ChargeBackController implements Serializable {
    
    @EJB
    private ChargeBackMDao chargeBackMDao;
    @EJB
    private ChargeBackDao chargeBackDao;
    
    @EJB
    private LogService logService;
    
    private ChargeBackFilter chargeBackFilter;
    
    private Date startDate = null, endDate = null;
    
    private PaginationHelper paginationUnauth, pagination, paginationMerchant;
    
    private DataModel unauthdataModel, dataModel, dataModelMerchant;
    
    public PaginationHelper getPagination() {

        if (pagination == null) {
            pagination = new PaginationHelper(50) {
                @Override
                public long getItemsCount() {
                    return chargeBackDao.count();
                }

                @Override
                public DataModel createPageDataModel() {
                    try {
                        return new ListDataModel(chargeBackDao.find(getPageFirstItem(), getPageSize(), startDate, endDate, null, null, getChargeBackFilter().getCurrency(), 0, null).getContent());
                    } catch (DatabaseException ex) {
                        Logger.getLogger(ProductDao.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    return new ListDataModel();
                }
            };
        }

        return pagination;
    }
    
    public PaginationHelper getPaginationMerchant() {

        if (paginationMerchant == null) {
            paginationMerchant = new PaginationHelper(50) {
                @Override
                public long getItemsCount() {
                    return chargeBackDao.count();
                }

                @Override
                public DataModel createPageDataModel() {
                    try {
                        return new ListDataModel(chargeBackDao.find(getPageFirstItem(), getPageSize()).getContent());
                    } catch (DatabaseException ex) {
                        Logger.getLogger(ProductDao.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    return new ListDataModel();
                }
            };
        }

        return paginationMerchant;
    }
    
    public DataModel getAll() {

        Session session = SecurityUtils.getSubject().getSession();

        Object obj = session.getAttribute("cchargeupdated");

        boolean status = obj == null ? false : Boolean.valueOf(obj + "");

        if (status == true) {
            pagination = null;
            session.setAttribute("cchargeupdated", false);
        }

        if (pagination == null) {
            dataModel = getPagination().createPageDataModel();
        }

        Log log = new Log();
        log.setAction("Fetch All Charge Back ");
        log.setCreatedOn(new Date());
        log.setDescription("Fetching All charge back ");
        log.setLevel(LogLevel.Info);
        log.setStatus(LogStatus.SUCCESSFUL);
        log.setUsername(SecurityUtils.getSubject().getPrincipal() + "");
        log.setLogDomain(LogDomain.ADMIN);
        log.setLogState(LogState.FINISH);

        logService.log(log, null);

        return dataModel;
    }
    
    public DataModel getAllByMerchant() {

        Session session = SecurityUtils.getSubject().getSession();

        Object obj = session.getAttribute("cchargeupdated");

        boolean status = obj == null ? false : Boolean.valueOf(obj + "");

        if (status == true) {
            paginationMerchant = null;
            session.setAttribute("cchargeupdated", false);
        }

        if (paginationMerchant == null) {
            dataModelMerchant = getPagination().createPageDataModel();
        }

        Log log = new Log();
        log.setAction("Fetch All Charge Back ");
        log.setCreatedOn(new Date());
        log.setDescription("Fetching All charge back ");
        log.setLevel(LogLevel.Info);
        log.setStatus(LogStatus.SUCCESSFUL);
        log.setUsername(SecurityUtils.getSubject().getPrincipal() + "");
        log.setLogDomain(LogDomain.ADMIN);
        log.setLogState(LogState.FINISH);

        logService.log(log, null);

        return dataModelMerchant;
    }
    
    /**
     * This called to reload 
     */
    public void recreate() {
        pagination = null;
        paginationUnauth = null;
    }
    
    
    public DataModel getUnauth() {

        Session session = SecurityUtils.getSubject().getSession();

        Object obj = session.getAttribute("cchargeupdatedm");

        boolean status = obj == null ? false : Boolean.valueOf(obj + "");

        if (status == true) {
            paginationUnauth = null;
            unauthdataModel = null;
            session.setAttribute("cchargeupdatedm", false);
        }

//        Log log = new Log();
//        log.setAction("Fetch All Unauth ");
//        log.setCreatedOn(new Date());
//        log.setDescription("Fetching All Unauth ");
//        log.setLevel(LogLevel.Info);
//        log.setStatus(LogStatus.SUCCESSFUL);
//        log.setUsername(SecurityUtils.getSubject().getPrincipal() + "");
//        log.setLogDomain(LogDomain.ADMIN);
//        log.setLogState(LogState.FINISH);
//
//        logService.log(log, null);

        if (paginationUnauth == null || unauthdataModel == null) {
            unauthdataModel = getPaginationUnauth().createPageDataModel();
        }

        return unauthdataModel;
    }
    
    public PaginationHelper getPaginationUnauth() {

        if (paginationUnauth == null) {
            paginationUnauth = new PaginationHelper(50) {
                @Override
                public long getItemsCount() {
                    return chargeBackMDao.countUnauth();
                }

                @Override
                public DataModel createPageDataModel() {
                    try {
                        return new ListDataModel(chargeBackMDao.findUnauth(getPageFirstItem(), getPageSize()).getContent());
                    } catch (DatabaseException ex) {
                        Logger.getLogger(ProductDao.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    return new ListDataModel();
                }
            };
        }

        return paginationUnauth;
    }
    
    /**
     * @return the chargeBackFilter
     */
    public ChargeBackFilter getChargeBackFilter() {
        
        if(chargeBackFilter == null)
            chargeBackFilter = new ChargeBackFilter();
        
        return chargeBackFilter;
    }

    /**
     * @param chargeBackFilter the chargeBackFilter to set
     */
    public void setChargeBackFilter(ChargeBackFilter chargeBackFilter) {
        this.chargeBackFilter = chargeBackFilter;
    }
    
    public String filter(){
        
        String range = chargeBackFilter.getRange();
        
        startDate = null;
        endDate = null;
        
        if (range != null && !range.equalsIgnoreCase("")) {

            try {
                String[] splitDate = range.split("-");

                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

                startDate = dateFormat.parse(splitDate[0]);
                endDate = dateFormat.parse(splitDate[1]);
            } catch (ParseException pe) {
                startDate = endDate = null;
            }

        }
       
        pagination = null;
        
        return null;
    }
    
    public String clearFilter(){
        
        startDate = endDate = null;
        pagination = null;
        
        chargeBackFilter = new ChargeBackFilter();
        
        return "list";
    }
    
}

src/main/webapp/chargeback/unauth.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:composition template="/template/template.xhtml">
        <ui:define name="title">Charge Back | Flutter MS</ui:define>
        <ui:define name="nav-title">All unauthorized Charge Back</ui:define>
        <ui:define name="styles">
            <h:outputStylesheet name="/css/sweetalert.css" />
            <h:outputStylesheet>
                
                table{
                    font-size: 0.70em;
                    width : 100%
                }
                table.dataTable thead > tr > th{
                    font-size: 80% !important;
                    text-align:center;
                }
                table.dataTable tbody > tr > td{
                    text-align:center;
                }
                
                .table td, .table th{
                    padding: 0.6rem !important;
                }
                
                .dataTables_filter{
                    display : none;
                }
                .fixed-size {
                    table-layout: fixed;
                    word-wrap: break-word;
                }
            </h:outputStylesheet>
        </ui:define>   
        <ui:define name="content">
            <div class="row">
                <h:panelGroup layout="block" class="col-lg-12">
                    <div class="card">
                        <div class="card-header no-bg b-a-0">Unauthorized Charge Back</div>
                        
                        <div class="card-block">
                            <p>See below for list of charge backs.</p>
                            
                            <div class="table-responsive">
                                
                                <c:if test="#{userController.hasRoles('ADD_CHARGEBACK')}"> 
                                    <h:link outcome="/chargeback/create" style="float: right" class="btn btn-primary btn-sm m-r-xs pull-right" value="Add Charge Back" />
                                </c:if>
                                <!--<h:link outcome="/chargeback/create" class="btn btn-danger btn-sm m-r-xs pull-right" style="margin-right: 2%" value="View Unauthorized" />-->
                                
                                <br /><br/>
                                <h:dataTable value="#{chargebackController.unauth}" var="item" class="table table-bordered table-striped m-b-0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all">
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Id"/>
                                    </f:facet>
                                    <h:outputText value="#{chargebackController.unauth.rowIndex + 1}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Flutterwave Reference"/>
                                    </f:facet>
                                    <h:outputText value="#{item.flwReference}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Authentication Type"/>
                                    </f:facet>
                                    <h:outputText value="#{item.authenticationType}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Amount"/>
                                    </f:facet>
                                    <h:outputText value="#{item.amount}"/>
                                </h:column>    
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Currency"/>
                                    </f:facet>
                                    <h:outputText value="#{item.currency}"/>
                                </h:column>      
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Created On"/>
                                    </f:facet>
                                    <h:outputText value="#{item.createdOn}">
                                        <f:convertDateTime pattern="MM/dd/yyyy hh:mm:ss a" />
                                    </h:outputText>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Operation"/>
                                    </f:facet>
                                    <h:outputText value="#{item.modelId == 0 ? 'CREATE' : 'UPDATE'}" />
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Created By"/>
                                    </f:facet>
                                    <h:outputText value="#{item.createdBy.firstName} #{item.createdBy.lastName}">
                                        <f:convertDateTime pattern="E, dd/MM/yyyy hh:mm:ss a" />
                                    </h:outputText>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="&nbsp;"/>
                                    </f:facet>
                                    <h:outputText value=" "/>
                                    <h:form rendered="#{item.status != 'APPROVED'}">
                                        <h:commandLink class="btn btn-success btn-sm m-r-xs" onclick="approve('#{item.id}', '#{item.flwReference}')" title="click to approve">
                                            <i class="icon-check"></i>
                                            <f:ajax render="@none" />
                                        </h:commandLink>
                                        <h:outputText value=" " />
                                        <h:commandLink class="btn btn-danger btn-sm m-r-xs" onclick="reject('#{item.id}', '#{item.flwReference}')" title="click to reject">
                                            <i class="icon-times"></i>
                                            <f:ajax render="@none" />
                                        </h:commandLink>
                                    </h:form>
                                    
                                    <h:outputText value=" "/>
                                </h:column>
                            </h:dataTable>
                            </div>
                        </div>
                    </div>
                </h:panelGroup>
            </div>
        </ui:define>
        <ui:define name="scripts">
            <h:outputScript name="/js/sweetalert.min.js" />
            <h:outputScript>
                
                var ctx = "#{request.contextPath}";
                
                function approve(id, name){
                    swal({
                    title: '<small>Charge Back Authorization</small>'
                        , text: 'Are you sure you want to approve this chargeback with reference<b>'+name+'</b> ?'
                        , type: 'warning'
                        ,animation: "slide-from-top"
                        , showCancelButton: true
                        , cancelButtonText: 'Cancel'
                        , closeOnConfirm: false
                        , confirmButtonText: 'OK'
                        , showLoaderOnConfirm: true
                        , html : true
                    }, function (isConfirm) {
                        
                        if(isConfirm === true || isConfirm === 'true'){
                            
                            $.ajax({
                                url: ctx + "/api/chargeback/authorize",
                                type: 'POST',
                                data : JSON.stringify({
                                    "operation" : "approve",
                                    "id" : id
                                }),
                                contentType : "application/json"
                            }).done(function( data ){

                                var statusCode = data['status-code'];

                                if(statusCode === "00" || statusCode == "00"){
                                    swal({
                                    title: '<span style="font-size: 80%">Charge Back Approved successfully</span>'
                                        , text: ''
                                        , type: 'success'
                                        , showCancelButton: false
                                        , confirmButtonText: 'OK'
                                        , closeOnConfirm: true
                                        , html: true
                                    }, function (isConfirm) {
                                        window.location.reload(true);
                                    });
                                }else
                                    swal('Authorization Failed', ''+data['status'], 'error');
                            }).fail(function(){
                                swal('Authorization Failed', '', 'error');
                            })
                        }
                    });
                }
    
                
                function reject(id, name){
                    swal({
                    title: '<small>Charge Back Authorization</small>'
                        , text: 'Are you sure you want to reject this for chargeback <b>'+name+'</b> ?'
                        , type: 'input'
                        , animation: "slide-from-top"
                        , showCancelButton: true
                        , cancelButtonText: 'Cancel'
                        , closeOnConfirm: false
                        , confirmButtonText: 'OK'
                        , inputPlaceholder: "Please provide reason for rejecting this update"
                        , showLoaderOnConfirm: true
                        , html : true
                    }, function (inputValue) {

                        if (inputValue === false) return false;

                        if (inputValue === "") {
                        swal.showInputError("<small>You need to provide reason for rejection!</small>");
                          return false;
                        }


                        $.ajax({
                            url: ctx + "/api/chargeback/authorize",
                            type: 'POST',
                            data : JSON.stringify({
                                "operation" : "reject",
                                "id" : id,
                                "rejectionMessage" : inputValue+""
                            }),
                            contentType : "application/json"
                            
                        }).done(function( data ){

                            var statusCode = data['status-code'];

                            if(statusCode === "00" || statusCode == "00"){
                                swal({
                                title: '<span style="font-size: 80%">Update Rejected Successfully</span>'
                                    , text: ''
                                    , type: 'success'
                                    , showCancelButton: false
                                    , confirmButtonText: 'OK'
                                    , closeOnConfirm: true
                                    , html: true
                                }, function (isConfirm) {
                                    window.location.reload(true);
                                });
                            }else
                                swal('Authorization Failed', ''+data['status'], 'error');
                        }).fail(function(){
                            swal('Authorization Failed', '', 'error');
                        })
                    });
                }
            </h:outputScript>
        </ui:define>
    </ui:composition>
</html>